#!/usr/bin/env python3
# Copyright 2026 Gijs Bos
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Build the Hermit CRM website from content.toml.

    python3 build.py            build site/index.html and site/app-tokens.css once
    python3 build.py --watch    rebuild whenever content.toml, style.css or the app's tokens change
    python3 build.py --share    also render site/img/og.png (needs Playwright)
    python3 build.py --release  build, then fail if any [TBC], "#" link or brief problem is left

Only the Python standard library is needed (3.11 or newer) for the page.
All words come from content.toml; the look is in site/style.css. Colours and
fonts shared with the app come from src/hermitcrm/static/tokens.css, copied into
site/app-tokens.css on every build. The build fails if the site uses a token
that neither file defines, so the site cannot drift from the app unnoticed.
"""
from __future__ import annotations

import html
import re
import sys
import time
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CONTENT = ROOT / "content.toml"
SITE = ROOT / "site"
OUT = SITE / "index.html"
STYLE = SITE / "style.css"
TOKENS = ROOT.parent / "src" / "hermitcrm" / "static" / "tokens.css"
APP_TOKENS = SITE / "app-tokens.css"

# Tokens from tokens.css that mean the same on the site as in the app. They are
# defined for the whole page; the rest (the app's palette) only inside the
# drawn app, so names like --muted cannot clash with the site's own.
SHARED = ("--brand", "--ink", "--sans", "--mono", "--serif")

BANNED = ["revolutionary", "supercharge", "seamless", "unlock", "powerful",
          "effortless", "game-changing", "next-generation", "ai-powered"]

# The Hermit CRM mark, cropped to the frame (from hermitcrm-mark.svg). The ink
# parts follow the text colour, so the mark works on light and dark paper.
MARK = ('<svg viewBox="4.5 10.5 55 43" aria-hidden="true" focusable="false">'
        '<rect x="7" y="13" width="50" height="38" rx="7" fill="none" stroke="currentColor" stroke-width="5"/>'
        '<circle cx="24" cy="27" r="5.5" fill="#1E8A60"/>'
        '<path d="M16 43 a8 8 0 0 1 16 0 z" fill="#1E8A60"/>'
        '<rect x="38" y="25" width="12" height="4" rx="2" fill="currentColor"/>'
        '<rect x="38" y="34" width="8" height="4" rx="2" fill="currentColor"/></svg>')


class BuildError(Exception):
    """Something the page cannot be built with; the message says what."""


# ── Tokens shared with the app ───────────────────────────────────────
def declarations(block: str) -> list[tuple[str, str]]:
    return [(m.group(1), " ".join(m.group(2).split()))
            for m in re.finditer(r"(--[\w-]+)\s*:\s*([^;]+);", block)]


def uncomment(css: str) -> str:
    return re.sub(r"/\*.*?\*/", "", css, flags=re.S)


def app_tokens_css(tokens: str) -> str:
    """site/app-tokens.css from the app's tokens.css: brand and type for the whole
    page, the app palette scoped to the drawn app (.mock-box)."""
    css = uncomment(tokens)
    main = re.search(r"^:root \{(.*?)^\}", css, re.S | re.M)
    fallback = re.search(r"@supports not \(color: light-dark\(#000, #fff\)\) \{\s*:root \{(.*?)\}", css, re.S)
    themes = re.findall(r'^\[data-theme="(\w+)"\]\s*\{\s*color-scheme:\s*([^;]+);\s*\}', css, re.M)
    if not main or not fallback or not themes:
        raise BuildError(f"{TOKENS} no longer has the :root block, the @supports "
                         "fallback and the [data-theme] rules this build reads")
    decls = declarations(main.group(1))
    shared = [d for d in decls if d[0] in SHARED]
    missing = set(SHARED) - {n for n, _ in shared}
    if missing:
        raise BuildError(f"tokens.css no longer defines {', '.join(sorted(missing))}")
    palette = [d for d in decls if d[0] not in SHARED]
    scheme = re.search(r"color-scheme:\s*([^;]+);", main.group(1)).group(1)
    line = lambda n, v: f"  {n}: {v};"  # noqa: E731
    out = ["/* GENERATED by website/build.py from src/hermitcrm/static/tokens.css.",
           "   Do not edit: change tokens.css (the app's defaults) and rebuild. */", "",
           "/* brand and type, the same on the site as in the app */",
           ":root {", *(line(n, v) for n, v in shared), "}", "",
           "/* the app's palette, only inside the drawn app */",
           ".mock-box {", f"  color-scheme: {scheme};", *(line(n, v) for n, v in palette), "}"]
    out += [f'.mock-box[data-theme="{name}"] {{ color-scheme: {value}; }}' for name, value in themes]
    out += ["", "@supports not (color: light-dark(#000, #fff)) {", "  .mock-box {",
            *("  " + line(n, v) for n, v in declarations(fallback.group(1))), "  }",
            "  .mock-box[data-theme] { color-scheme: light; }", "}", ""]
    return "\n".join(out)


def drift(site_css: str, app_css: str) -> list[str]:
    """Tokens the site uses but nobody defines. Inside the drawn app (.mock rules)
    a token must come from the app, not from the site's look-alike of the same name."""
    # The app's names are the ones in its main blocks; the @supports fallback
    # only repeats them for old browsers and must not keep a renamed one alive.
    site_css, app_css = uncomment(site_css), uncomment(app_css).split("@supports", 1)[0]
    defined = lambda css: {n for n, _ in declarations(css)}  # noqa: E731
    app_defined, site_defined = defined(app_css), defined(site_css)
    problems = [f"site/style.css uses {n}, which neither style.css nor tokens.css defines"
                for n in sorted(set(re.findall(r"var\((--[\w-]+)", site_css)) - app_defined - site_defined)]
    mock_rules = [body for sel, body in re.findall(r"([^{}]+)\{([^{}]*)\}", site_css) if ".mock" in sel]
    mock_own = defined("".join(mock_rules))  # e.g. --u, the drawing's unit
    for n in sorted({n for body in mock_rules for n in re.findall(r"var\((--[\w-]+)", body)}
                    - app_defined - mock_own):
        problems.append(f"the drawn app uses {n}, which the app's tokens.css does not define")
    return problems


# ── Text helpers ─────────────────────────────────────────────────────
def flat(text: str) -> str:
    """Join a multi-line TOML string into one line."""
    return " ".join(text.split())


def md(text: str) -> str:
    """Escape, then apply **bold**, `code` and [text](url)."""
    out = html.escape(flat(text), quote=False)
    codes: list[str] = []

    def keep_code(m: re.Match) -> str:
        codes.append(f"<code>{m.group(1)}</code>")
        return f"\x00{len(codes) - 1}\x00"

    out = re.sub(r"`([^`]+)`", keep_code, out)
    out = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", out)
    out = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)",
                 lambda m: f'<a href="{html.escape(m.group(2))}">{m.group(1)}</a>', out)
    return re.sub(r"\x00(\d+)\x00", lambda m: codes[int(m.group(1))], out)


def attr(text: str) -> str:
    return html.escape(flat(text), quote=True)


# ── Page parts ───────────────────────────────────────────────────────
def meta_line(c: dict) -> str:
    r = c["release"]
    return f'<p class="meta">Version {md(r["version"])} · {md(r["license"])}</p>'


def download_block(c: dict) -> str:
    return (f'<div class="download">\n'
            f'  <a class="btn" href="{attr(c["links"]["download"])}">{md(c["hero"]["download_button"])}</a>\n'
            f'  {meta_line(c)}\n</div>')


def mock() -> str:
    cols = [("Prospect", [("Acme BV", "NL · today", True), ("Globex GmbH", "DE · 3 days", False),
                          ("Initech SARL", "FR · 1 week", False)]),
            ("Engaged", [("Umbrella NV", "BE · 2 days", False), ("Hooli Ltd", "GB · 5 days", False)]),
            ("Discovery", [("Soylent AG", "CH · 4 days", False), ("Stark &amp; Co", "NL · 2 weeks", False)]),
            ("Offer", [("Wonka BV", "NL · 6 days", False)]),
            ("Won", [("Vandelay SA", "FR · 3 weeks", False)])]
    nav = ["Home", "Pipeline", "Calendar", "Companies", "Contacts", "Messages", "Extension",
           "Reports", "Settings", "Help"]  # same order as the app sidebar (templates/base.html)
    side = "".join(f'<div class="mock-nav{" on" if n == "Pipeline" else ""}">{n}</div>' for n in nav)
    board = "".join(
        f'<div class="mock-col"><div class="mock-h"><span>{h}</span><span>{len(cards)}</span></div>'
        + "".join(f'<div class="mock-card{" hi" if hi else ""}"><b>{n}</b><small>{m}</small></div>'
                  for n, m, hi in cards)
        + "</div>" for h, cards in cols)
    return (f'<div class="mock-box" data-theme="system" role="img" aria-label="Placeholder drawing of the pipeline board">'
            f'<div class="mock" aria-hidden="true">'
            f'<div class="mock-side"><div class="mock-brand">{MARK}<span>Hermit CRM</span></div>{side}</div>'
            f'<div class="mock-main"><div class="mock-top"><div class="mock-title">Pipeline</div>'
            f'<div class="mock-tag">Placeholder · real screenshot [TBC]</div></div>'
            f'<div class="mock-cols">{board}</div></div></div></div>')


def render(c: dict) -> str:
    p, h, i, f = c["page"], c["hero"], c["install"], c["file"]
    description = flat(p["description"] or h["subline"])
    site_url = p["site_url"].rstrip("/")
    og = ""
    if site_url:
        og = (f'<meta property="og:url" content="{attr(site_url)}/">\n'
              f'<meta property="og:image" content="{attr(site_url)}/img/og.png">\n')
    github = f'<a href="{attr(c["links"]["github"])}">{md(c["header"]["github_label"])}</a>'

    steps = "\n".join(f"      <li><span>{md(s)}</span></li>" for s in i["steps"])
    features = "\n".join(f"      <dt>{md(x['name'])}</dt><dd>{md(x['text'])}</dd>"
                         for x in c["features"]["items"])
    principles = "\n".join(f"      <p><strong>{md(x['name'])}</strong> {md(x['text'])}</p>"
                           for x in c["principles"])
    faqs = "\n".join(
        f'      <details{" open" if q.get("open") else ""}><summary>{md(q["q"])}</summary>'
        f'<p>{md(q["a"])}</p></details>' for q in c["questions"]["items"])

    if f["screenshot"]:
        visual = (f'<img src="img/{attr(f["screenshot"])}" alt="{attr(f["screenshot_alt"])}" '
                  f'width="1600" height="800" loading="lazy">')
    else:
        visual = mock()
    file_body = html.escape(f["file_body"].strip("\n"))
    sha256 = f'<a href="{attr(c["links"]["sha256"])}">{md(h["sha256_label"])}</a>'
    footer = (md(c["footer"]["text"].replace("{github}", "\x01").replace("{sha256}", "\x02"))
              .replace("\x01", github).replace("\x02", sha256))

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{attr(p["title"])}</title>
<meta name="description" content="{attr(description)}">
<meta property="og:type" content="website">
<meta property="og:title" content="{attr(p["title"])}">
<meta property="og:description" content="{attr(description)}">
{og}<meta name="twitter:card" content="summary_large_image">
<meta name="theme-color" content="#F5F1E8" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#1C1B18" media="(prefers-color-scheme: dark)">
<link rel="icon" href="img/favicon.svg" type="image/svg+xml">
<link rel="icon" href="img/favicon-32.png" sizes="32x32" type="image/png">
<link rel="apple-touch-icon" href="img/apple-touch-icon.png">
<link rel="stylesheet" href="app-tokens.css">
<link rel="stylesheet" href="style.css">
</head>
<body>
<!-- Built from content.toml by build.py. Edit the text there, not here. -->
<a class="skip" href="#main">Skip to content</a>

<header class="site-header wide">
  <a class="brand" href="./" aria-label="{attr(c["header"]["name"])} home">{MARK}<span>{md(c["header"]["name"])}</span></a>
  {github}
</header>

<main id="main">
  <section class="hero col">
    <h1>{md(h["h1"])}</h1>
    <p class="subline">{md(h["subline"])}</p>
    {download_block(c)}

    <div class="install">
      <h2 class="label">{md(i["label"])}</h2>
      <ol class="steps">
{steps}
      </ol>
      <div class="card indent">
        <p class="message" id="install-message">{md(i["message"])}</p>
        <button class="copy" type="button" hidden data-copy="{attr(i["message"])}" data-done="{attr(i["copied_label"])}"
                data-failed="{attr(i["copy_failed_label"])}"
                aria-label="Copy the install message"><span aria-live="polite">{md(i["copy_button"])}</span></button>
      </div>
    </div>
  </section>

  <hr class="rule">

  <section class="idea wide" aria-labelledby="idea">
    <div class="narrow">
      <p class="label">{md(f["label"])}</p>
      <h2 class="big" id="idea">{md(f["heading"])}</h2>
    </div>
    <div class="idea-grid">
      <figure class="window">
        <div class="window-bar"><i></i><i></i><i></i><span>{md(f["address_bar"])}</span></div>
        {visual}
      </figure>
      <div class="file">
        <p>{md(f["file_caption"])}</p>
        <pre><span class="path">{html.escape(f["file_path"])}</span>
{file_body}</pre>
      </div>
    </div>
  </section>

  <hr class="rule">

  <section class="features col" aria-labelledby="features">
    <h2 class="label" id="features">{md(c["features"]["label"])}</h2>
    <dl>
{features}
    </dl>
    <div class="principles">
{principles}
    </div>
  </section>

  <hr class="rule">

  <section class="questions col" aria-labelledby="questions">
    <h2 class="label" id="questions">{md(c["questions"]["label"])}</h2>
    <div>
{faqs}
    </div>
  </section>
</main>

<footer class="site-footer col">{footer}</footer>

<script>
// Copy button: shown only when scripts run. "Copied" only when the copy
// worked; otherwise the message is selected and the button says how to copy.
document.querySelectorAll("[data-copy]").forEach(function (btn) {{
  var label = btn.querySelector("span"), idle = label.textContent, timer;
  var message = document.getElementById("install-message");
  btn.hidden = false;
  function show(text, ms) {{
    label.textContent = text;
    clearTimeout(timer);
    timer = setTimeout(function () {{ label.textContent = idle; }}, ms);
  }}
  function done() {{ show(btn.dataset.done, 2000); }}
  function failed() {{
    var range = document.createRange(), sel = window.getSelection();
    range.selectNodeContents(message); sel.removeAllRanges(); sel.addRange(range);
    show(btn.dataset.failed, 4000);
  }}
  function fallback(text) {{
    var t = document.createElement("textarea"), ok = false;
    t.value = text; t.setAttribute("readonly", ""); t.style.position = "fixed"; t.style.opacity = "0";
    document.body.appendChild(t); t.select();
    try {{ ok = document.execCommand("copy"); }} catch (e) {{}}
    document.body.removeChild(t);
    ok ? done() : failed();
  }}
  btn.addEventListener("click", function () {{
    var text = btn.dataset.copy;
    if (navigator.clipboard && window.isSecureContext) {{
      navigator.clipboard.writeText(text).then(done, function () {{ fallback(text); }});
    }} else {{ fallback(text); }}
  }});
}});
// Printing: open every answer, then put them back as they were.
var shut = [];
addEventListener("beforeprint", function () {{
  shut = [].filter.call(document.querySelectorAll("details"), function (d) {{ return !d.open; }});
  shut.forEach(function (d) {{ d.open = true; }});
}});
addEventListener("afterprint", function () {{ shut.forEach(function (d) {{ d.open = false; }}); }});
</script>
</body>
</html>
"""


# ── Checks against the brief ─────────────────────────────────────────
def walk(value, path=""):
    if isinstance(value, str):
        yield path, value
    elif isinstance(value, dict):
        for k, v in value.items():
            yield from walk(v, f"{path}.{k}" if path else k)
    elif isinstance(value, list):
        for n, v in enumerate(value, 1):
            yield from walk(v, f"{path}[{n}]")


def check(c: dict) -> tuple[list[str], list[str]]:
    problems, tbc = [], []
    for path, text in walk(c):
        if path == "file.file_body":
            continue
        if "—" in text or "–" in text:
            problems.append(f"{path}: em or en dash")
        if "!" in text:
            problems.append(f"{path}: exclamation mark")
        low = text.lower()
        for word in BANNED:
            if re.search(rf"\b{re.escape(word)}", low):
                problems.append(f"{path}: banned word '{word}'")
        if "[TBC" in text or text.strip() == "#" and path.startswith("links."):
            tbc.append(path)
    for p in problems:
        print(f"  warning  {p}")
    if tbc:
        print(f"  {len(tbc)} values still [TBC]: " + ", ".join(tbc))
    if c["file"]["screenshot"] and not (SITE / "img" / c["file"]["screenshot"]).exists():
        problems.append(f"site/img/{c['file']['screenshot']} does not exist")
        print(f"  warning  {problems[-1]}")
    return problems, tbc


def build() -> tuple[dict, list[str], list[str]]:
    """Build both files; raise BuildError when the site and the app have drifted."""
    app_css = app_tokens_css(TOKENS.read_text(encoding="utf-8"))
    broken = drift(STYLE.read_text(encoding="utf-8"), app_css)
    if broken:
        raise BuildError("the site no longer matches the app's tokens:\n  " + "\n  ".join(broken))
    c = tomllib.loads(CONTENT.read_text(encoding="utf-8"))
    APP_TOKENS.write_text(app_css, encoding="utf-8")
    OUT.write_text(render(c), encoding="utf-8")
    print(f"built {OUT.relative_to(ROOT)} and {APP_TOKENS.relative_to(ROOT)}")
    problems, tbc = check(c)
    return c, problems, tbc


def share(c: dict) -> None:
    """Render the 1200 x 630 share image with Playwright."""
    from playwright.sync_api import sync_playwright  # pip install playwright

    page_html = f"""<!doctype html><html><head><meta charset="utf-8">
<link rel="stylesheet" href="app-tokens.css"><link rel="stylesheet" href="style.css"><style>
:root{{color-scheme:light}} body{{margin:0;width:1200px;height:630px;overflow:hidden}}
.s{{width:1200px;height:630px;box-sizing:border-box;padding:96px 120px;display:flex;flex-direction:column;justify-content:space-between}}
.s .brand svg{{width:58px;height:46px}} .s .brand span{{font-size:38px}}
.s h1{{font-size:112px;line-height:1}} .s p{{margin:0;font-size:28px;color:var(--muted)}}
</style></head><body><div class="s">
<div class="brand">{MARK}<span>{md(c["header"]["name"])}</span></div>
<div><h1>{md(c["hero"]["h1"])}</h1></div>
<p>{md(c["share"]["tagline"])}</p></div></body></html>"""
    tmp = SITE / "_share.html"
    tmp.write_text(page_html, encoding="utf-8")
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch()
            page = browser.new_page(viewport={"width": 1200, "height": 630})
            page.goto(tmp.as_uri())
            page.evaluate("document.fonts.ready")
            page.screenshot(path=str(SITE / "img" / "og.png"))
            browser.close()
    finally:
        tmp.unlink(missing_ok=True)
    print("built site/img/og.png")


def main() -> None:
    try:
        c, problems, tbc = build()
    except BuildError as e:
        sys.exit(f"build failed: {e}")
    if "--release" in sys.argv and (problems or tbc):
        sys.exit(f"not ready to release: {len(tbc)} [TBC] or '#' values and "
                 f"{len(problems)} problems left (listed above)")
    if "--share" in sys.argv:
        share(c)
    if "--watch" in sys.argv:
        watched = [CONTENT, STYLE, TOKENS]
        print("watching content.toml, site/style.css and the app's tokens.css (Ctrl+C to stop)")
        stamp = lambda: [f.stat().st_mtime for f in watched]  # noqa: E731
        seen = stamp()
        while True:
            time.sleep(0.5)
            now = stamp()
            if now != seen:
                seen = now
                try:
                    build()
                except tomllib.TOMLDecodeError as e:
                    print(f"  content.toml has a mistake: {e}")
                except BuildError as e:
                    print(f"  build failed: {e}")


if __name__ == "__main__":
    main()
